[package]
name = "leetcode-2020-06-11"
version = "0.1.0"
authors = ["Will Marsman <william.marsman@mdacorporation.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
